import { Author, Book, Category, Coupon, StoreSettings } from "../types";

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: "cat-amharic-lit",
    name: "Amharic Literature",
    slug: "amharic-literature",
    description: "Classic and contemporary Ethiopian novels, poetry, and prose written in Amharic.",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 12
  },
  {
    id: "cat-fiction",
    name: "Fiction & Novels",
    slug: "fiction-novels",
    description: "Captivating stories, literary masterpieces, and bestselling global novels.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 18
  },
  {
    id: "cat-history",
    name: "Ethiopian History & Heritage",
    slug: "ethiopian-history",
    description: "Deep dive into ancient Aksum, Lalibela, Adwa, and modern Ethiopian history.",
    image: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 9
  },
  {
    id: "cat-business",
    name: "Business & Entrepreneurship",
    slug: "business-entrepreneurship",
    description: "Finance, leadership, startup strategy, and economics for builders.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 14
  },
  {
    id: "cat-self-dev",
    name: "Self-Development & Personal Growth",
    slug: "self-development",
    description: "Mindset, productivity, discipline, and building lifelong healthy habits.",
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 15
  },
  {
    id: "cat-tech",
    name: "Technology & Software Engineering",
    slug: "technology-engineering",
    description: "Coding, AI, system design, data science, and modern software architectures.",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 10
  },
  {
    id: "cat-children",
    name: "Children & Young Adult",
    slug: "children-young-adult",
    description: "Bilingual storybooks, Ethiopian folktales, and fun learning for kids.",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    active: true,
    bookCount: 8
  }
];

export function generateBookCoverSvg(
  titleAmharic: string,
  titleEnglish: string,
  author: string,
  category: string,
  bgGradient: [string, string],
  accentColor: string,
  symbol: string
): string {
  const cleanId = titleEnglish.replace(/[^a-zA-Z0-9]/g, "");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 600" width="400" height="600">
    <defs>
      <linearGradient id="bg-${cleanId}" x1="0%" y1="0%" x2="100%" y2="100%">
        <stop offset="0%" stop-color="${bgGradient[0]}" />
        <stop offset="100%" stop-color="${bgGradient[1]}" />
      </linearGradient>
      <linearGradient id="gold-${cleanId}" x1="0%" y1="0%" x2="100%" y2="0%">
        <stop offset="0%" stop-color="#F59E0B" />
        <stop offset="50%" stop-color="#FEF08A" />
        <stop offset="100%" stop-color="#D97706" />
      </linearGradient>
    </defs>

    <!-- Book Cover Base Background -->
    <rect width="400" height="600" fill="url(#bg-${cleanId})" rx="8" />
    
    <!-- Spine Line Shadow -->
    <rect x="0" y="0" width="18" height="600" fill="#000000" opacity="0.25" />
    <line x1="18" y1="0" x2="18" y2="600" stroke="#FFFFFF" stroke-opacity="0.15" stroke-width="1.5" />

    <!-- Outer Decorative Border Frame -->
    <rect x="28" y="24" width="344" height="552" fill="none" stroke="${accentColor}" stroke-width="2" stroke-dasharray="6,4" opacity="0.6" rx="4" />
    <rect x="34" y="30" width="332" height="540" fill="none" stroke="${accentColor}" stroke-width="1" opacity="0.8" rx="2" />

    <!-- Category Header Pill -->
    <rect x="80" y="55" width="240" height="24" fill="#000000" opacity="0.4" rx="12" />
    <text x="200" y="71" font-family="sans-serif" font-size="10" font-weight="900" fill="${accentColor}" text-anchor="middle" letter-spacing="1.5">${category.toUpperCase()}</text>

    <!-- Center Icon Symbol / Emblem -->
    <circle cx="200" cy="170" r="48" fill="#000000" opacity="0.3" stroke="${accentColor}" stroke-width="2" />
    <text x="200" y="184" font-family="sans-serif" font-size="36" text-anchor="middle">${symbol}</text>

    <!-- Main Title (Amharic) -->
    <text x="200" y="275" font-family="'Noto Sans Ethiopic', 'Abyssinica SIL', 'Nyala', sans-serif" font-size="25" font-weight="900" fill="#FFFFFF" text-anchor="middle">
      ${titleAmharic}
    </text>

    <!-- Subtitle (English Translation) -->
    <text x="200" y="315" font-family="sans-serif" font-size="13" font-weight="600" fill="${accentColor}" text-anchor="middle" letter-spacing="1">
      ${titleEnglish}
    </text>

    <line x1="80" y1="350" x2="320" y2="350" stroke="url(#gold-${cleanId})" stroke-width="2" />

    <!-- Author Badge -->
    <text x="200" y="435" font-family="sans-serif" font-size="10" font-weight="800" fill="#94A3B8" text-anchor="middle" letter-spacing="2">AUTHOR / ደራሲ</text>
    <text x="200" y="465" font-family="'Noto Sans Ethiopic', 'Abyssinica SIL', sans-serif" font-size="19" font-weight="800" fill="#FFFFFF" text-anchor="middle">
      ${author}
    </text>

    <!-- Publisher Seal / Seal Footer -->
    <rect x="100" y="520" width="200" height="22" fill="${accentColor}" opacity="0.2" rx="4" />
    <text x="200" y="535" font-family="sans-serif" font-size="9" font-weight="900" fill="${accentColor}" text-anchor="middle" letter-spacing="1.5">JJ BOOKSHOPPING • 🇪🇹</text>
  </svg>`;

  return `data:image/svg+xml;utf8,${encodeURIComponent(svg)}`;
}

export function getValidBookCover(book: Partial<Book>): string {
  // If book has a valid photographic URL and is not an SVG data URI or broken link, return it
  if (
    book.coverImage &&
    book.coverImage.length > 20 &&
    !book.coverImage.startsWith("data:image/svg")
  ) {
    return book.coverImage;
  }

  const title = (book.title || "").trim();
  const titleLower = title.toLowerCase();
  const slug = (book.slug || "").toLowerCase();
  const id = (book.id || "").toLowerCase();

  if (titleLower.includes("fiqir") || titleLower.includes("ፍቅር") || slug.includes("fiqir") || id.includes("fiqir")) {
    return "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("oromay") || titleLower.includes("ኦሮማይ") || slug.includes("oromay") || id.includes("oromay")) {
    return "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("yetoqolefebet") || titleLower.includes("ቁልፍ") || slug.includes("kulf") || id.includes("kulf")) {
    return "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("egre") || titleLower.includes("እግረ") || slug.includes("egre") || id.includes("egre")) {
    return "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("alweledim") || titleLower.includes("አልወለድም") || slug.includes("alweledim") || id.includes("alweledim")) {
    return "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("bashager") || titleLower.includes("አድማስ") || slug.includes("bashager") || id.includes("bashager")) {
    return "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("derasew") || titleLower.includes("ደራሲው") || slug.includes("derasew") || id.includes("derasew")) {
    return "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("hiwete") || titleLower.includes("ሕይወቴና") || slug.includes("hiwete") || id.includes("hiwete")) {
    return "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("yesat") || titleLower.includes("እሳት") || slug.includes("yesat") || id.includes("yesat")) {
    return "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("taytu") || titleLower.includes("ጣይቱ") || slug.includes("taytu") || id.includes("taytu")) {
    return "https://images.unsplash.com/photo-1599839575945-a9e5af0c3fa5?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("mahlet") || titleLower.includes("ማህሌት") || slug.includes("mahlet") || id.includes("mahlet")) {
    return "https://images.unsplash.com/photo-1507838153414-b4b713384a76?auto=format&fit=crop&w=800&q=80";
  }
  if (titleLower.includes("lenes") || titleLower.includes("ለእኔስ") || slug.includes("lenes") || id.includes("lenes")) {
    return "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&w=800&q=80";
  }

  // Fallback high quality book photography
  return "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80";
}

export const INITIAL_AUTHORS: Author[] = [
  {
    id: "auth-haddis",
    name: "Haddis Alemayehu (ሀዲስ ዓለማየሁ)",
    slug: "haddis-alemayehu",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
    bio: "Renowned Ethiopian statesman and novelist, author of the landmark Amharic masterpiece 'Fiqir Eske Mequabir' (Love unto the Crypt).",
    active: true,
    bookCount: 1
  },
  {
    id: "auth-bealu",
    name: "Bealu Girma (በአሉ ግርማ)",
    slug: "bealu-girma",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    bio: "Prominent Ethiopian journalist, author, and literary icon who wrote 'Oromay', 'Keadmas Bashager', and 'Derasew'.",
    active: true,
    bookCount: 3
  },
  {
    id: "auth-mehret",
    name: "Dr. Mehret Debebe (ዶ/ር ምሕረት ደበበ)",
    slug: "dr-mehret-debebe",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    bio: "Renowned psychiatrist, speaker, and author of bestselling Amharic personal transformation books including 'Yetoqolefebet Kulf' and 'Egre Menged'.",
    active: true,
    bookCount: 2
  },
  {
    id: "auth-abe-gubegna",
    name: "Abe Gubegna (ዓቤ ጉበኛ)",
    slug: "abe-gubegna",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    bio: "Famous Ethiopian novelist and playwright best known for his philosophical and social justice novel 'Alweledim'.",
    active: true,
    bookCount: 1
  },
  {
    id: "auth-haile-selassie",
    name: "Emperor Haile Selassie I (ቀዳማዊ ኃይለ ሥላሴ)",
    slug: "haile-selassie",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80",
    bio: "Emperor of Ethiopia whose autobiography 'Hiwete ena YeEthiopia Erimja' chronicles modern Ethiopian history and international diplomacy.",
    active: true,
    bookCount: 1
  },
  {
    id: "auth-tsegaye",
    name: "Laureate Tsegaye Gebre-Medhin (ሎሬ特 ፀጋዬ ገብረመድህን)",
    slug: "tsegaye-gebre-medhin",
    image: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&auto=format&fit=crop&q=80",
    bio: "Poet Laureate of Ethiopia, playwright, art director, and author of 'Yesat Wey Abeba'.",
    active: true,
    bookCount: 1
  },
  {
    id: "auth-lapiso",
    name: "Prof. Lapiso G. Dilebo (ፕሮፌሰር ላፕሶ ጌታሁን)",
    slug: "lapiso-dilebo",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
    bio: "Ethiopian historian and scholar documenting the Battle of Adwa and the leadership of Empress Taytu Betul.",
    active: true,
    bookCount: 1
  },
  {
    id: "auth-birhanu",
    name: "Birhanu Zerihun (ብርሃኑ ዘሪሁን)",
    slug: "birhanu-zerihun",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    bio: "Celebrated Ethiopian writer and journalist, author of 'Mahlet', 'YeTebeka Wuha', and historical trilogies.",
    active: true,
    bookCount: 1
  },
  {
    id: "auth-adam-reta",
    name: "Adam Reta (አዳም ረጣ)",
    slug: "adam-reta",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    bio: "Master of contemporary Amharic fiction, innovator of the 'Ultra-Nebelbal' literary style, author of 'Lenes Maneh' and 'Zhantoz'.",
    active: true,
    bookCount: 1
  }
];

export const INITIAL_BOOKS: Book[] = [
  {
    "id": "book-1-ke-admas-bashager",
    "title": "ከአድማስ ባሻገር (Ke Admas Bashager)",
    "slug": "ke-admas-bashager",
    "description": "A masterwork by Baalu Girma. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-baalu-girma",
    "authorName": "Baalu Girma",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 13.99,
    "currency": "ETB",
    "coverImage": "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1437481485i/25950435.jpg",
    "ISBN": "978-99944-75-230-0",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 348,
    "language": "Amharic",
    "stock": 25,
    "soldCount": 83,
    "ratingAverage": 5,
    "reviewCount": 17,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.936Z",
    "updatedAt": "2026-08-18T05:46:13.936Z"
  },
  {
    "id": "book-2-fikir-eske-mekabir",
    "title": "ፍቅር እስከ መቃብር (Fikir Eske Mekabir)",
    "slug": "fikir-eske-mekabir",
    "description": "A masterwork by Haddis Alemayehu. Category: Classic Literature. Published in Amharic & English literature collection.",
    "authorId": "auth-haddis-alemayehu",
    "authorName": "Haddis Alemayehu",
    "categoryId": "cat-classic-literature",
    "categoryName": "Classic Literature",
    "price": 18,
    "currency": "ETB",
    "coverImage": "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1436443449i/25877188.jpg",
    "ISBN": "978-99944-17-790-1",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 341,
    "language": "Amharic",
    "stock": 45,
    "soldCount": 16,
    "ratingAverage": 4.8,
    "reviewCount": 39,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.936Z",
    "updatedAt": "2026-08-18T05:46:13.936Z"
  },
  {
    "id": "book-3-yetekolefebet-kulf",
    "title": "የተቆለፈበት ቁልፍ (Yetekolefebet Kulf)",
    "slug": "yetekolefebet-kulf",
    "description": "A masterwork by Dr. Mehret Debebe. Category: Psychology/Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-mehret-debebe",
    "authorName": "Dr. Mehret Debebe",
    "categoryId": "cat-psychologyfiction",
    "categoryName": "Psychology/Fiction",
    "price": 16.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-71-481-2",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 400,
    "language": "Amharic",
    "stock": 35,
    "soldCount": 89,
    "ratingAverage": 4.8,
    "reviewCount": 34,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.936Z",
    "updatedAt": "2026-08-18T05:46:13.936Z"
  },
  {
    "id": "book-4-emegua",
    "title": "እመጓ (Emegua)",
    "slug": "emegua",
    "description": "A masterwork by Dr. Alemayehu Wase. Category: Mystery/Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-alemayehu-wase",
    "authorName": "Dr. Alemayehu Wase",
    "categoryId": "cat-mysteryfiction",
    "categoryName": "Mystery/Fiction",
    "price": 14.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-70-796-3",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 448,
    "language": "Amharic",
    "stock": 40,
    "soldCount": 144,
    "ratingAverage": 4.7,
    "reviewCount": 42,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-5-tikusat",
    "title": "ትኩሳት (Tikusat)",
    "slug": "tikusat",
    "description": "A masterwork by Sibhat Gebregziabher. Category: Romance. Published in Amharic & English literature collection.",
    "authorId": "auth-sibhat-gebregziabher",
    "authorName": "Sibhat Gebregziabher",
    "categoryId": "cat-romance",
    "categoryName": "Romance",
    "price": 12.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-43-637-4",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 425,
    "language": "Amharic",
    "stock": 20,
    "soldCount": 26,
    "ratingAverage": 4.7,
    "reviewCount": 39,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-6-oromay",
    "title": "ኦሮማይ (Oromay)",
    "slug": "oromay",
    "description": "A masterwork by Baalu Girma. Category: Historical Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-baalu-girma",
    "authorName": "Baalu Girma",
    "categoryId": "cat-historical-fiction",
    "categoryName": "Historical Fiction",
    "price": 15.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-50-789-5",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 339,
    "language": "Amharic",
    "stock": 30,
    "soldCount": 81,
    "ratingAverage": 4.4,
    "reviewCount": 51,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-7-sememen",
    "title": "ሰመመን (Sememen)",
    "slug": "sememen",
    "description": "A masterwork by Sisay Nigusu. Category: Romance/Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-sisay-nigusu",
    "authorName": "Sisay Nigusu",
    "categoryId": "cat-romancefiction",
    "categoryName": "Romance/Fiction",
    "price": 11.99,
    "currency": "ETB",
    "coverImage": "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1440148810i/26138910.jpg",
    "ISBN": "978-99944-61-626-6",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 240,
    "language": "Amharic",
    "stock": 22,
    "soldCount": 112,
    "ratingAverage": 4.9,
    "reviewCount": 46,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-8-ke-amen-bashager",
    "title": "ከአሜን ባሻገር (Ke Amen Bashager)",
    "slug": "ke-amen-bashager",
    "description": "A masterwork by Bewketu Seyoum. Category: Short Stories. Published in Amharic & English literature collection.",
    "authorId": "auth-bewketu-seyoum",
    "authorName": "Bewketu Seyoum",
    "categoryId": "cat-short-stories",
    "categoryName": "Short Stories",
    "price": 13,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-67-644-7",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 462,
    "language": "Amharic",
    "stock": 50,
    "soldCount": 36,
    "ratingAverage": 4.6,
    "reviewCount": 7,
    "featured": true,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-9-lela-sew",
    "title": "ሌላ ሰው (Lela Sew)",
    "slug": "lela-sew",
    "description": "A masterwork by Dr. Mehret Debebe. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-mehret-debebe",
    "authorName": "Dr. Mehret Debebe",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 16,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-28-694-8",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 338,
    "language": "Amharic",
    "stock": 18,
    "soldCount": 48,
    "ratingAverage": 4.3,
    "reviewCount": 21,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-10-alweledm",
    "title": "አልወለድም (Alweledm)",
    "slug": "alweledm",
    "description": "A masterwork by Abe Gubegna. Category: Fiction/Philosophy. Published in Amharic & English literature collection.",
    "authorId": "auth-abe-gubegna",
    "authorName": "Abe Gubegna",
    "categoryId": "cat-fictionphilosophy",
    "categoryName": "Fiction/Philosophy",
    "price": 12.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-32-736-9",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 335,
    "language": "Amharic",
    "stock": 15,
    "soldCount": 121,
    "ratingAverage": 4.8,
    "reviewCount": 26,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-11-mahlet",
    "title": "ማህሌት (Mahlet)",
    "slug": "mahlet",
    "description": "A masterwork by Sibhat Gebregziabher. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-sibhat-gebregziabher",
    "authorName": "Sibhat Gebregziabher",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 11.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-68-508-10",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 469,
    "language": "Amharic",
    "stock": 12,
    "soldCount": 50,
    "ratingAverage": 4.4,
    "reviewCount": 21,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-12-dertogada",
    "title": "ዴርቶጋዳ (Dertogada)",
    "slug": "dertogada",
    "description": "A masterwork by Yismake Worku. Category: Sci-Fi/Thriller. Published in Amharic & English literature collection.",
    "authorId": "auth-yismake-worku",
    "authorName": "Yismake Worku",
    "categoryId": "cat-sci-fithriller",
    "categoryName": "Sci-Fi/Thriller",
    "price": 19.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-57-520-11",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 233,
    "language": "Amharic",
    "stock": 60,
    "soldCount": 132,
    "ratingAverage": 4.8,
    "reviewCount": 34,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-13-ramatohara",
    "title": "ራማቶሓራ (Ramatohara)",
    "slug": "ramatohara",
    "description": "A masterwork by Yismake Worku. Category: Sci-Fi/Thriller. Published in Amharic & English literature collection.",
    "authorId": "auth-yismake-worku",
    "authorName": "Yismake Worku",
    "categoryId": "cat-sci-fithriller",
    "categoryName": "Sci-Fi/Thriller",
    "price": 19.99,
    "currency": "ETB",
    "coverImage": "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1484609682i/33871399.jpg",
    "ISBN": "978-99944-75-736-12",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 225,
    "language": "Amharic",
    "stock": 45,
    "soldCount": 126,
    "ratingAverage": 4.8,
    "reviewCount": 36,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-14-zhantozhara",
    "title": "ዣንቶዣራ (Zhantozhara)",
    "slug": "zhantozhara",
    "description": "A masterwork by Yismake Worku. Category: Sci-Fi/Thriller. Published in Amharic & English literature collection.",
    "authorId": "auth-yismake-worku",
    "authorName": "Yismake Worku",
    "categoryId": "cat-sci-fithriller",
    "categoryName": "Sci-Fi/Thriller",
    "price": 19.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-47-108-13",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 455,
    "language": "Amharic",
    "stock": 38,
    "soldCount": 80,
    "ratingAverage": 4.6,
    "reviewCount": 36,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-15-yoratorad",
    "title": "ዮራቶራድ (Yoratorad)",
    "slug": "yoratorad",
    "description": "A masterwork by Yismake Worku. Category: Sci-Fi/Thriller. Published in Amharic & English literature collection.",
    "authorId": "auth-yismake-worku",
    "authorName": "Yismake Worku",
    "categoryId": "cat-sci-fithriller",
    "categoryName": "Sci-Fi/Thriller",
    "price": 19.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-27-464-14",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 452,
    "language": "Amharic",
    "stock": 50,
    "soldCount": 12,
    "ratingAverage": 4.8,
    "reviewCount": 21,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-16-ye-burka-zimita",
    "title": "የቡርቃ ዝምታ (Ye Burka Zimita)",
    "slug": "ye-burka-zimita",
    "description": "A masterwork by Tesfaye Gebreab. Category: Historical Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-tesfaye-gebreab",
    "authorName": "Tesfaye Gebreab",
    "categoryId": "cat-historical-fiction",
    "categoryName": "Historical Fiction",
    "price": 17.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-36-992-15",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 198,
    "language": "Amharic",
    "stock": 25,
    "soldCount": 146,
    "ratingAverage": 4.7,
    "reviewCount": 19,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-17-ye-gazetegnaw-mastawesha",
    "title": "የጋዜጠኛው ማስታወሻ (Ye Gazetegnaw Mastawesha)",
    "slug": "ye-gazetegnaw-mastawesha",
    "description": "A masterwork by Tesfaye Gebreab. Category: Memoir/Politics. Published in Amharic & English literature collection.",
    "authorId": "auth-tesfaye-gebreab",
    "authorName": "Tesfaye Gebreab",
    "categoryId": "cat-memoirpolitics",
    "categoryName": "Memoir/Politics",
    "price": 16.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-89-998-16",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 211,
    "language": "Amharic",
    "stock": 15,
    "soldCount": 140,
    "ratingAverage": 4.7,
    "reviewCount": 46,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-18-tertaw-sew",
    "title": "ተርታው ሰው (Tertaw Sew)",
    "slug": "tertaw-sew",
    "description": "A masterwork by Enkuayehu Bekele. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-enkuayehu-bekele",
    "authorName": "Enkuayehu Bekele",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 10.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-28-413-17",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 441,
    "language": "Amharic",
    "stock": 10,
    "soldCount": 105,
    "ratingAverage": 4.4,
    "reviewCount": 24,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-19-reyot",
    "title": "ርዕዮት (Reyot)",
    "slug": "reyot",
    "description": "A masterwork by Fikremarkos Desta. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-fikremarkos-desta",
    "authorName": "Fikremarkos Desta",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 14.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-67-650-18",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 352,
    "language": "Amharic",
    "stock": 30,
    "soldCount": 115,
    "ratingAverage": 4.8,
    "reviewCount": 13,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-20-ye-hilina-dewel",
    "title": "የሕሊና ደወል (Ye Hilina Dewel)",
    "slug": "ye-hilina-dewel",
    "description": "A masterwork by Haddis Alemayehu. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-haddis-alemayehu",
    "authorName": "Haddis Alemayehu",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 15,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-76-182-19",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 285,
    "language": "Amharic",
    "stock": 20,
    "soldCount": 129,
    "ratingAverage": 4.4,
    "reviewCount": 40,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-21-tewodros",
    "title": "ቴዎድሮስ (Tewodros)",
    "slug": "tewodros",
    "description": "A masterwork by Abbe Gubegna. Category: Historical Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-abbe-gubegna",
    "authorName": "Abbe Gubegna",
    "categoryId": "cat-historical-fiction",
    "categoryName": "Historical Fiction",
    "price": 13.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-48-539-20",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 465,
    "language": "Amharic",
    "stock": 28,
    "soldCount": 48,
    "ratingAverage": 5,
    "reviewCount": 46,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-22-maebel",
    "title": "ማዕበል (Maebel)",
    "slug": "maebel",
    "description": "A masterwork by Birhanu Zerihun. Category: Historical Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-birhanu-zerihun",
    "authorName": "Birhanu Zerihun",
    "categoryId": "cat-historical-fiction",
    "categoryName": "Historical Fiction",
    "price": 18.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-38-547-21",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 437,
    "language": "Amharic",
    "stock": 35,
    "soldCount": 59,
    "ratingAverage": 4.4,
    "reviewCount": 8,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-23-medemer",
    "title": "መደመር (Medemer)",
    "slug": "medemer",
    "description": "A masterwork by Abiy Ahmed. Category: Politics/Philosophy. Published in Amharic & English literature collection.",
    "authorId": "auth-abiy-ahmed",
    "authorName": "Abiy Ahmed",
    "categoryId": "cat-politicsphilosophy",
    "categoryName": "Politics/Philosophy",
    "price": 20,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-19-371-22",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 435,
    "language": "Amharic",
    "stock": 100,
    "soldCount": 147,
    "ratingAverage": 4.8,
    "reviewCount": 5,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-24-ye-tibeb-menged",
    "title": "የጥበብ መንገድ (Ye Tibeb Menged)",
    "slug": "ye-tibeb-menged",
    "description": "A masterwork by Dr. Mehret Debebe. Category: Psychology/Self-Help. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-mehret-debebe",
    "authorName": "Dr. Mehret Debebe",
    "categoryId": "cat-psychologyself-help",
    "categoryName": "Psychology/Self-Help",
    "price": 15.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-14-996-23",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 463,
    "language": "Amharic",
    "stock": 42,
    "soldCount": 107,
    "ratingAverage": 4.8,
    "reviewCount": 23,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-25-7tegnaw-melak",
    "title": "7ተኛው መልአክ (7tegnaw Melak)",
    "slug": "7tegnaw-melak",
    "description": "A masterwork by Sibhat Gebregziabher. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-sibhat-gebregziabher",
    "authorName": "Sibhat Gebregziabher",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 11.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-76-363-24",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 470,
    "language": "Amharic",
    "stock": 19,
    "soldCount": 151,
    "ratingAverage": 4.3,
    "reviewCount": 34,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-26-adafne",
    "title": "አዳፍኔ (Adafne)",
    "slug": "adafne",
    "description": "A masterwork by Dagnachew Worku. Category: Classic Literature. Published in Amharic & English literature collection.",
    "authorId": "auth-dagnachew-worku",
    "authorName": "Dagnachew Worku",
    "categoryId": "cat-classic-literature",
    "categoryName": "Classic Literature",
    "price": 14,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-26-959-25",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 384,
    "language": "Amharic",
    "stock": 24,
    "soldCount": 103,
    "ratingAverage": 4.4,
    "reviewCount": 15,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-27-romeo-and-juliet",
    "title": "ሮሜኦ እና ዡልየት (Romeo and Juliet)",
    "slug": "romeo-and-juliet",
    "description": "A masterwork by William Shakespeare. Category: Romance/Play. Published in Amharic & English literature collection.",
    "authorId": "auth-william-shakespeare",
    "authorName": "William Shakespeare",
    "categoryId": "cat-romanceplay",
    "categoryName": "Romance/Play",
    "price": 9.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-33-110-26",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 184,
    "language": "Amharic",
    "stock": 15,
    "soldCount": 86,
    "ratingAverage": 4.9,
    "reviewCount": 54,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-28-haddis",
    "title": "ሐዲስ (Haddis)",
    "slug": "haddis",
    "description": "A masterwork by Baalu Girma. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-baalu-girma",
    "authorName": "Baalu Girma",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 13.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-85-365-27",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 324,
    "language": "Amharic",
    "stock": 26,
    "soldCount": 61,
    "ratingAverage": 4.5,
    "reviewCount": 16,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-29-derasiw",
    "title": "ደራሲው (Derasiw)",
    "slug": "derasiw",
    "description": "A masterwork by Baalu Girma. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-baalu-girma",
    "authorName": "Baalu Girma",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 14.5,
    "currency": "ETB",
    "coverImage": "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1439386401i/26087481.jpg",
    "ISBN": "978-99944-48-302-28",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 315,
    "language": "Amharic",
    "stock": 20,
    "soldCount": 84,
    "ratingAverage": 5,
    "reviewCount": 27,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-30-yehiwot-kimem",
    "title": "የህይወት ቅመም (Yehiwot Kimem)",
    "slug": "yehiwot-kimem",
    "description": "A masterwork by Daniel Kibret. Category: Non-Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-daniel-kibret",
    "authorName": "Daniel Kibret",
    "categoryId": "cat-non-fiction",
    "categoryName": "Non-Fiction",
    "price": 12,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-12-872-29",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 387,
    "language": "Amharic",
    "stock": 55,
    "soldCount": 113,
    "ratingAverage": 4.7,
    "reviewCount": 17,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-31-andit-midir-lijoch",
    "title": "አንዲት ምድር ልጆች (Andit Midir Lijoch)",
    "slug": "andit-midir-lijoch",
    "description": "A masterwork by Amare Tegbaru. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-amare-tegbaru",
    "authorName": "Amare Tegbaru",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 11.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-95-100-30",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 492,
    "language": "Amharic",
    "stock": 14,
    "soldCount": 55,
    "ratingAverage": 4.9,
    "reviewCount": 26,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-32-inba-ena-sak",
    "title": "ዕንባ እና ሳቅ (Inba Ena Sak)",
    "slug": "inba-ena-sak",
    "description": "A masterwork by Girmachew Teklehawariat. Category: Classic Literature. Published in Amharic & English literature collection.",
    "authorId": "auth-girmachew-teklehawariat",
    "authorName": "Girmachew Teklehawariat",
    "categoryId": "cat-classic-literature",
    "categoryName": "Classic Literature",
    "price": 16,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-28-579-31",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 423,
    "language": "Amharic",
    "stock": 30,
    "soldCount": 103,
    "ratingAverage": 5,
    "reviewCount": 13,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-33-birhan-ena-selam",
    "title": "ብርሀን እና ሰላም (Birhan Ena Selam)",
    "slug": "birhan-ena-selam",
    "description": "A masterwork by Blatten Geta Heruy Welde Selassie. Category: Classic Literature. Published in Amharic & English literature collection.",
    "authorId": "auth-blatten-geta-heruy-welde-selassie",
    "authorName": "Blatten Geta Heruy Welde Selassie",
    "categoryId": "cat-classic-literature",
    "categoryName": "Classic Literature",
    "price": 17.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-91-965-32",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 419,
    "language": "Amharic",
    "stock": 12,
    "soldCount": 108,
    "ratingAverage": 4.4,
    "reviewCount": 45,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-34-yelib-weled-iwneta",
    "title": "የልብ ወለድ እውነታ (Yelib Weled Iwneta)",
    "slug": "yelib-weled-iwneta",
    "description": "A masterwork by Bewketu Seyoum. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-bewketu-seyoum",
    "authorName": "Bewketu Seyoum",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 14,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-14-779-33",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 333,
    "language": "Amharic",
    "stock": 48,
    "soldCount": 88,
    "ratingAverage": 4.6,
    "reviewCount": 40,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-35-girdosh",
    "title": "ግርዶሽ (Girdosh)",
    "slug": "girdosh",
    "description": "A masterwork by Adam Reta. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-adam-reta",
    "authorName": "Adam Reta",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 15.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-37-335-34",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 382,
    "language": "Amharic",
    "stock": 33,
    "soldCount": 46,
    "ratingAverage": 4.9,
    "reviewCount": 9,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-36-addis-ababa",
    "title": "አዲስ አበባ (Addis Ababa)",
    "slug": "addis-ababa",
    "description": "A masterwork by Awgachew Terefe. Category: Short Stories. Published in Amharic & English literature collection.",
    "authorId": "auth-awgachew-terefe",
    "authorName": "Awgachew Terefe",
    "categoryId": "cat-short-stories",
    "categoryName": "Short Stories",
    "price": 10.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-94-829-35",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 220,
    "language": "Amharic",
    "stock": 25,
    "soldCount": 92,
    "ratingAverage": 4.5,
    "reviewCount": 32,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-37-ye-tizita-feleg",
    "title": "የትዝታ ፈለግ (Ye Tizita Feleg)",
    "slug": "ye-tizita-feleg",
    "description": "A masterwork by Tesfaye Gebreab. Category: Memoir. Published in Amharic & English literature collection.",
    "authorId": "auth-tesfaye-gebreab",
    "authorName": "Tesfaye Gebreab",
    "categoryId": "cat-memoir",
    "categoryName": "Memoir",
    "price": 16.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-59-775-36",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 434,
    "language": "Amharic",
    "stock": 17,
    "soldCount": 57,
    "ratingAverage": 4.6,
    "reviewCount": 8,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-38-mahilete-tsige",
    "title": "ማኅሌተ ጽጌ (Mahilete Tsige)",
    "slug": "mahilete-tsige",
    "description": "A masterwork by Adam Reta. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-adam-reta",
    "authorName": "Adam Reta",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 13.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-57-442-37",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 436,
    "language": "Amharic",
    "stock": 20,
    "soldCount": 115,
    "ratingAverage": 4.3,
    "reviewCount": 39,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-39-sibara-atint",
    "title": "ስባራ አጥንት (Sibara Atint)",
    "slug": "sibara-atint",
    "description": "A masterwork by Adam Reta. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-adam-reta",
    "authorName": "Adam Reta",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 14.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-88-649-38",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 248,
    "language": "Amharic",
    "stock": 22,
    "soldCount": 158,
    "ratingAverage": 4.4,
    "reviewCount": 44,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-40-alemenor",
    "title": "አለመኖር (Alemenor)",
    "slug": "alemenor",
    "description": "A masterwork by Dawit Wondimagegn. Category: Psychology. Published in Amharic & English literature collection.",
    "authorId": "auth-dawit-wondimagegn",
    "authorName": "Dawit Wondimagegn",
    "categoryId": "cat-psychology",
    "categoryName": "Psychology",
    "price": 18,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-69-947-39",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 251,
    "language": "Amharic",
    "stock": 40,
    "soldCount": 59,
    "ratingAverage": 4.5,
    "reviewCount": 43,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-41-ziguara",
    "title": "ዝጓራ (Ziguara)",
    "slug": "ziguara",
    "description": "A masterwork by Yismake Worku. Category: Thriller. Published in Amharic & English literature collection.",
    "authorId": "auth-yismake-worku",
    "authorName": "Yismake Worku",
    "categoryId": "cat-thriller",
    "categoryName": "Thriller",
    "price": 19,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-63-396-40",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 357,
    "language": "Amharic",
    "stock": 65,
    "soldCount": 23,
    "ratingAverage": 4.5,
    "reviewCount": 43,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-42-ye-negew-sew",
    "title": "የነገው ሰው (Ye Negew Sew)",
    "slug": "ye-negew-sew",
    "description": "A masterwork by Dr. Eyob Mamo. Category: Self-Help. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-eyob-mamo",
    "authorName": "Dr. Eyob Mamo",
    "categoryId": "cat-self-help",
    "categoryName": "Self-Help",
    "price": 12.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-46-810-41",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 305,
    "language": "Amharic",
    "stock": 80,
    "soldCount": 114,
    "ratingAverage": 4.7,
    "reviewCount": 45,
    "featured": false,
    "newArrival": false,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-43-ignyam-innuribet",
    "title": "እኛም እንኑርበት (Ignyam Innuribet)",
    "slug": "ignyam-innuribet",
    "description": "A masterwork by Dr. Rodas Tadese. Category: Science/Philosophy. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-rodas-tadese",
    "authorName": "Dr. Rodas Tadese",
    "categoryId": "cat-sciencephilosophy",
    "categoryName": "Science/Philosophy",
    "price": 17.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-40-987-42",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 384,
    "language": "Amharic",
    "stock": 55,
    "soldCount": 138,
    "ratingAverage": 4.9,
    "reviewCount": 35,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-44-aemirowon-yazeminu",
    "title": "አዕምሮዎን ያዘምኑ (Aemirowon Yazeminu)",
    "slug": "aemirowon-yazeminu",
    "description": "A masterwork by Dr. Eyob Mamo. Category: Self-Help. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-eyob-mamo",
    "authorName": "Dr. Eyob Mamo",
    "categoryId": "cat-self-help",
    "categoryName": "Self-Help",
    "price": 13.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-76-770-43",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 412,
    "language": "Amharic",
    "stock": 70,
    "soldCount": 69,
    "ratingAverage": 4.6,
    "reviewCount": 5,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-45-iletawi-nuro",
    "title": "ዕለታዊ ኑሮ (Iletawi Nuro)",
    "slug": "iletawi-nuro",
    "description": "A masterwork by Dr. Eyob Mamo. Category: Self-Help. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-eyob-mamo",
    "authorName": "Dr. Eyob Mamo",
    "categoryId": "cat-self-help",
    "categoryName": "Self-Help",
    "price": 12,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-26-984-44",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 366,
    "language": "Amharic",
    "stock": 60,
    "soldCount": 107,
    "ratingAverage": 4.7,
    "reviewCount": 6,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-46-meklit",
    "title": "መክሊት (Meklit)",
    "slug": "meklit",
    "description": "A masterwork by Dr. Eyob Mamo. Category: Self-Help. Published in Amharic & English literature collection.",
    "authorId": "auth-dr-eyob-mamo",
    "authorName": "Dr. Eyob Mamo",
    "categoryId": "cat-self-help",
    "categoryName": "Self-Help",
    "price": 14,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-71-377-45",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 494,
    "language": "Amharic",
    "stock": 45,
    "soldCount": 74,
    "ratingAverage": 4.8,
    "reviewCount": 48,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-47-zimitaye",
    "title": "ዝምታዬ (Zimitaye)",
    "slug": "zimitaye",
    "description": "A masterwork by Fikremarkos Desta. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-fikremarkos-desta",
    "authorName": "Fikremarkos Desta",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 15,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-44-667-46",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 290,
    "language": "Amharic",
    "stock": 32,
    "soldCount": 138,
    "ratingAverage": 4.5,
    "reviewCount": 43,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-48-kebero",
    "title": "ከበሮ (Kebero)",
    "slug": "kebero",
    "description": "A masterwork by Teshome Birhanu. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-teshome-birhanu",
    "authorName": "Teshome Birhanu",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 11.99,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-83-146-47",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 357,
    "language": "Amharic",
    "stock": 16,
    "soldCount": 66,
    "ratingAverage": 4.9,
    "reviewCount": 32,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-49-kignit",
    "title": "ቅኝት (Kignit)",
    "slug": "kignit",
    "description": "A masterwork by Teshome Birhanu. Category: Fiction. Published in Amharic & English literature collection.",
    "authorId": "auth-teshome-birhanu",
    "authorName": "Teshome Birhanu",
    "categoryId": "cat-fiction",
    "categoryName": "Fiction",
    "price": 12.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-45-401-48",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 458,
    "language": "Amharic",
    "stock": 19,
    "soldCount": 12,
    "ratingAverage": 4.4,
    "reviewCount": 20,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  },
  {
    "id": "book-50-esat-wey-abeba",
    "title": "እሳት ወይ አበባ (Esat Wey Abeba)",
    "slug": "esat-wey-abeba",
    "description": "A masterwork by Tsegaye Gabre-Medhin. Category: Poetry. Published in Amharic & English literature collection.",
    "authorId": "auth-tsegaye-gabre-medhin",
    "authorName": "Tsegaye Gabre-Medhin",
    "categoryId": "cat-poetry",
    "categoryName": "Poetry",
    "price": 16.5,
    "currency": "ETB",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    "ISBN": "978-99944-21-554-49",
    "publisher": "JJ Bookstore Publishing",
    "publicationDate": "2021-01-15",
    "pages": 241,
    "language": "Amharic",
    "stock": 38,
    "soldCount": 131,
    "ratingAverage": 4.7,
    "reviewCount": 32,
    "featured": false,
    "newArrival": true,
    "active": true,
    "createdAt": "2026-08-18T05:46:13.937Z",
    "updatedAt": "2026-08-18T05:46:13.937Z"
  }
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: "coupon-welcome15",
    code: "WELCOME15",
    discountType: "percentage",
    discountValue: 15, // 15%
    minOrderAmount: 300,
    maxDiscount: 300,
    expirationDate: "2028-12-31",
    usageLimit: 1000,
    usedCount: 0,
    active: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "coupon-read200",
    code: "READ200",
    discountType: "fixed",
    discountValue: 200, // 200 ETB
    minOrderAmount: 1000,
    expirationDate: "2028-12-31",
    usageLimit: 500,
    usedCount: 0,
    active: true,
    createdAt: new Date().toISOString()
  },
  {
    id: "coupon-ethiopia10",
    code: "ETHIOPIA10",
    discountType: "percentage",
    discountValue: 10,
    minOrderAmount: 200,
    expirationDate: "2028-12-31",
    usageLimit: 2000,
    usedCount: 0,
    active: true,
    createdAt: new Date().toISOString()
  }
];

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  storeName: "JJ Book Shopping",
  logo: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=200&auto=format&fit=crop&q=80",
  email: "support@jjbookshopping.com",
  phone: "+251 938 014 055",
  address: "Bole Medhaniallem, JJ Bookstore Building, Addis Ababa, Ethiopia",
  currency: "ETB",
  shippingFee: 150,
  minFreeShipping: 1500,
  taxRate: 15, // 15% VAT
  storeStatus: "open",
  socialLinks: {
    facebook: "https://facebook.com/jjbookshopping",
    telegram: "https://t.me/jjbookshopping",
    instagram: "https://instagram.com/jjbookshopping"
  },
  paymentGateways: {
    codEnabled: true,
    telebirrEnabled: true,
    telebirrNumber: "+251938014055 (JJ Book Shopping)",
    cbeBirrEnabled: true,
    cbeAccountNumber: "1000123456789 (Commercial Bank of Ethiopia)",
    chapaEnabled: true,
    bankTransferEnabled: true,
    bankDetails: "Bank of Abyssinia (አቢሲንያ ባንክ) Account: 155832444 (JJ Book Shopping)"
  }
};
